language: python
cache: pip
os: linux

jobs:
  include:
    - python: 2.7
      dist: bionic
      env:
        - TOX_ENV=py27
    - python: 3.5
      dist: bionic
      env:
        - TOX_ENV=py35
    - python: 3.6
      dist: bionic
      env:
        - TOX_ENV=py36
    - python: 3.7
      dist: focal
      env:
        - TOX_ENV=py37
    - python: 3.8
      dist: focal
      env:
        - TOX_ENV=py38

install:
  - pip install tox
  - "if ! [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then pip install mypy; fi"

script:
  - "if ! [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then mypy pylti1p3/ && mypy --py2 pylti1p3/; fi"
  - tox -e $TOX_ENV

notifications:
  email:
    - dmitry.viskov@webenterprise.ru
