version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  toxify:
    docker:
      - image: circleci/python:3.8.11
    environment:
      TOXENV: py35,py36,py37,py38,py39
    steps:
      - checkout
      - run:
          name: Install utils
          command: sudo pip install tox
      - run:
          command: tox

workflows:
  build:
    jobs:
      - toxify
